version: '3.7'

services:
  gql:
    container_name: vobe-gql
    build:
      context: .
      target: node
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./vobe/:/vobe
      - ./bin/:/usr/src/app/bin
    ports:
      - 4000:4000

  mongo:
    image: mongo
    container_name: vobe-mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - .:/data/configdb

volumes:
  mongodata:
